#ifdef BEAN_SUCCESS

#undef BEAN_SUCCESS
#undef BEAN_FAIL 

#undef BEAN_BYTE
#undef BEAN_WORD16
#undef BEAN_WORD32

#undef BEAN_BYTE_TRANS 
#undef BEAN_WORD16_TRANS 
#undef BEAN_WORD32_TRANS 

#undef BEAN_BYTE_TRANS_WITH
#undef BEAN_WORD16_TRANS_WITH
#undef BEAN_WORD32_TRANS_WITH

#undef BEAN_BYTE_ARRAY
#undef BEAN_WORD16_ARRAY
#undef BEAN_WORD32_ARRAY

#undef BEAN_BYTE_ARRAY_ALIAS
#undef BEAN_WORD16_ARRAY_ALIAS
#undef BEAN_WORD32_ARRAY_ALIAS

#undef BEAN_BYTE_ARRAY_TRANS
#undef BEAN_WORD16_ARRAY_TRANS
#undef BEAN_WORD32_ARRAY_TRANS

#undef BEAN_BYTE_SIZE
#undef BEAN_WORD16_SIZE
#undef BEAN_WORD32_SIZE

#undef BEAN_BYTE_ALIAS
#undef BEAN_WORD16_ALIAS
#undef BEAN_WORD32_ALIAS

#undef BEAN_BYTE_MULT_NODES
#undef BEAN_WORD16_MULT_NODES
#undef BEAN_WORD32_MULT_NODES

#undef BEAN_BYTE_NOTFOUND
#undef BEAN_WORD16_NOTFOUND
#undef BEAN_WORD32_NOTFOUND

#undef BEAN_IF_HAS_ITEM

#undef BEAN_STRUCT
#undef BEAN_STRUCT_ARRAY

#undef BEAN_DEF
#undef BEAN_DEF_END

#undef BEAN_USE
#undef BEAN_HAS_KEY

#undef BEAN_INIT
#undef BEAN_USE_KEY
#undef BEAN_SUB_USE_KEY
#undef BEAN_SUB_ARRAY_USE_KEY
#undef BEAN_INIT_END
#undef BEAN_USE_KEY_WITH_INIT
    
#undef BEAN_DEF_WITH
#undef BEAN_DEF_END_WITH
#undef BEAN_DEF_END_WITH_INIT

#endif
